### ISSUE TITLE
prime-select broken after update to kernel 4.15.0-32 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by phybzu** [timrichardson/Prime-Ubuntu-18.04#4]
Last week I update my system and with it came kernel 4.15.0-32. After the update I got the following error message when running "sudo nvidia-prime nvidia":

"PKCS#7 signature not signed with a trusted key"

The message repeats over and over again until I reboot the system.

I switched to the Nvidia GPU using the prime-select version provided by Ubuntu and repeated the installations steps descibed in the readme, but it didn't help.
Is there something I can fix myself, or do you need to update your version of prime-select?
Thanks for the good work, I appreciate it!

**Comment by timrichardson** [comment]
please try sudo update-initramfs -u and reboot
If that doesn't work, purge and reinstall the nvidia drivers

I am using the same kernel without problems. 

This is nothing in the script which could be changed, I would say the kernel does not have the nvidia drivers installed properly.

**Comment by phybzu** [comment]
I've tried the steps you've suggested, it still happens. It's a test installation, so that might be the probelm :-)
