### ISSUE TITLE
nvidia module in use and cannot be removed when switching to intel

### ISSUE THREAD

**Issue by haggles** [timrichardson/Prime-Ubuntu-18.04#5]
I think I have successfully installed and configured this in Mint 19 on a Dell XPS 9560 (1050GTX) running 4.15.32, thanks for all your (and Matthieu's) work so far! I can switch to nvidia, and ignoring the signature issue, it works fine. Switching back to intel (my primary mode), it hangs on a black screen and needs a hard power off to recover. It then boots into intel mode, as indicated by the system tray icon. However, my power use was still high so I followed your debugging tips and found the nvidia module is still loaded.

Looking at the dmesg log:
```
$ dmesg | grep bbswitch
[   15.190178] bbswitch: version 0.8
[   15.190182] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
[   15.190187] bbswitch: Found discrete VGA device 0000:01:00.0: \_SB_.PCI0.PEG0.PEGP
[   15.190301] bbswitch: detected an Optimus _DSM function
[   15.190309] bbswitch: Succesfully loaded. Discrete card 0000:01:00.0 is on
[   15.190504] bbswitch: device 0000:01:00.0 is in use by driver 'nvidia', refusing OFF
```
Basically the same info in the systemctl status:
```
● nvidia-prime-boot.service - Unload nvidia modules and turn dGPU off during boot
   Loaded: loaded (/etc/systemd/system/nvidia-prime-boot.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2018-08-22 23:06:26 AEST; 2min 48s ago
  Process: 1027 ExecStart=/usr/local/bin/turnoff_nvidia_at_boot (code=exited, status=0/SUCCESS)
 Main PID: 1027 (code=exited, status=0/SUCCESS)

Aug 22 23:06:26 beaker systemd[1]: Starting Unload nvidia modules and turn dGPU off during boot...
Aug 22 23:06:26 beaker turnoff_nvidia_at_boot[1027]: rmmod: ERROR: Module nouveau is not currently loaded
Aug 22 23:06:26 beaker turnoff_nvidia_at_boot[1027]: rmmod: ERROR: Module nvidia is in use
Aug 22 23:06:26 beaker systemd[1]: Started Unload nvidia modules and turn dGPU off during boot.
```
Following your debugging guide:
```
$ sudo prime-select query
intel
$ lsmod | grep nvidia
nvidia              14340096  3
ipmi_msghandler        53248  2 nvidia,ipmi_devintf
$ lsmod | grep nouveau
<none>
```
Manually remove the modules:
```# rmmod nouveau
rmmod: ERROR: Module nouveau is not currently loaded
# rmmod nvidia_drm
rmmod: ERROR: Module nvidia_drm is not currently loaded
# rmmod nvidia_modeset
rmmod: ERROR: Module nvidia_modeset is not currently loaded
# rmmod nvidia_uvm
rmmod: ERROR: Module nvidia_uvm is not currently loaded
# rmmod nvidia
rmmod: ERROR: Module nvidia is in use
```
I had a poke around, but I can't see where this is loaded, it's not in /etc/X11 where I would expect it. Any suggestions for me to manually try?

**Comment by timrichardson** [comment]
What is ipmi_msghandler ?
This is something I don't recognise. Something is stopping the nvidia driver from unloading, I guess it is this. Add to your debugging steps an attempt to unload it, what ever it is, and let me know how you go.

**Comment by timrichardson** [comment]
see this too in case it helps: It is exactly your bug I think.
https://github.com/Bumblebee-Project/bbswitch/issues/173

**Comment by timrichardson** [comment]
You may also like to take this to the nvidia linux developers forum, it has gurus.

**Comment by timrichardson** [comment]
and which version of the nvidia driver are you using? I am using the 390 series (390.77)

**Comment by haggles** [comment]
Thanks for all the feedback, Tim. I'm using the stock 390 driver from Mint 19, which is currently 390.48 according to Driver Manager. Interesting that you have a different version... I wonder how much of a factor that is?

I have no idea where the ipmi_msghandler is coming from. Reading the linked issue in bbswitch seems like my exact problem.

I actually came across prime from a different angle - suspend doesn't work any more. See https://forums.linuxmint.com/viewtopic.php?t=274924 for the same issue on the same hardware. I looked in journalctl and saw something about nvidia, looked into the issues 4.15 seems to be having, and eventually found my way here. Your work seemed that it may be able to solve both my power consumption issue and my suspend issue! But it was not to be, at least yet.

I'll keep looking, and get back to you if I find anything interesting, but in the mean time I'll close this out because it's not an issue with your code. Cheers.

**Comment by timrichardson** [comment]
I was using 390.48 successfully for the past few months, I updated only in the last couple of days.

**Comment by haggles** [comment]
Well that's even more annoying!

For what it's worth, I followed your uninstall instructions and had a look at the modules in use when running with intel graphics - the nvidia module is not in use, but nouveau is. Ok, sure, whatever. My issue with suspend was with the nvidia module, so I tested suspend and it worked. The nvidia card is still running, and still consuming power, but I'm halfway to my goal.

**Comment by timrichardson** [comment]
I tested out the latest driver from the PPA (in the 396 series), it works too (Ubuntu 18.04, it's so good I have ditched Mint).

If you have nouveau running, your install is borked. It may be that nvidia is not installed properly. Go around again with the "additional drivers" install of nvidia. Perhaps try the standard prime-select intel and prime-select nvidia to convince yourself it is working.

nouveau and nvidia are killed by /usr/local/bin/turnoff_nvidia_at_boot
which is run from the service nvidia-prime-boot.service
This service is installed from prime-select intel (the modified prime-select). 

That is, when using this approach, you should see this service active in intel mode.
It's is easy to see how that script works: it just does a bunch of rmmods. 
You can go to virtual console, stop lightdm and then run them one at a time, to check that it works in principle. 

*** only install 'my' modified version from a working Nvidia session. Never use the standard prime-select or standard Nvidia GUI control panel to switch to Intel: the standard method will purge the nvidia drivers from the kernel when it swaps to Intel.
